# Generated by cpp11: do not edit by hand

adf_upper <- function(x, intl) {
  .Call(`_adfExplorer2_adf_upper`, x, intl)
}

adf_path_to_entry <- function(extptr, filename, mode) {
  .Call(`_adfExplorer2_adf_path_to_entry`, extptr, filename, mode)
}

adf_file_exists_ <- function(extptr, path) {
  .Call(`_adfExplorer2_adf_file_exists_`, extptr, path)
}

adf_dir_exists_ <- function(extptr, path) {
  .Call(`_adfExplorer2_adf_dir_exists_`, extptr, path)
}

adf_entry_info_ <- function(extptr, path) {
  .Call(`_adfExplorer2_adf_entry_info_`, extptr, path)
}

adf_change_dir <- function(extptr, path) {
  .Call(`_adfExplorer2_adf_change_dir`, extptr, path)
}

adf_get_current_dir <- function(extptr) {
  .Call(`_adfExplorer2_adf_get_current_dir`, extptr)
}

list_adf_entries_ <- function(extptr, filename, recursive, nested) {
  .Call(`_adfExplorer2_list_adf_entries_`, extptr, filename, recursive, nested)
}

adf_mkdir <- function(extptr, path) {
  .Call(`_adfExplorer2_adf_mkdir`, extptr, path)
}

adf_remove_entry <- function(extptr, path, flush) {
  .Call(`_adfExplorer2_adf_remove_entry`, extptr, path, flush)
}

adf_set_entry_name_ <- function(extptr, path, replacement) {
  .Call(`_adfExplorer2_adf_set_entry_name_`, extptr, path, replacement)
}

move_adf_internal <- function(extptr, source, destination) {
  .Call(`_adfExplorer2_move_adf_internal`, extptr, source, destination)
}

read_adf_block_ <- function(extptr, sector) {
  .Call(`_adfExplorer2_read_adf_block_`, extptr, sector)
}

write_adf_block_ <- function(extptr, sector, block) {
  .Call(`_adfExplorer2_write_adf_block_`, extptr, sector, block)
}

interpret_file_header <- function(extptr, vol_num, sectnum) {
  .Call(`_adfExplorer2_interpret_file_header`, extptr, vol_num, sectnum)
}

interpret_dir_header <- function(extptr, vol_num, sectnum) {
  .Call(`_adfExplorer2_interpret_dir_header`, extptr, vol_num, sectnum)
}

interpret_root_header <- function(extptr, vol_num) {
  .Call(`_adfExplorer2_interpret_root_header`, extptr, vol_num)
}

adf_dev_format <- function(extptr, name, ffs, intl, dircache, bootable) {
  .Call(`_adfExplorer2_adf_dev_format`, extptr, name, ffs, intl, dircache, bootable)
}

adf_dev_name <- function(extptr, vol_num) {
  .Call(`_adfExplorer2_adf_dev_name`, extptr, vol_num)
}

adf_dev_size <- function(extptr) {
  .Call(`_adfExplorer2_adf_dev_size`, extptr)
}

adf_dev_nvol <- function(exptr) {
  .Call(`_adfExplorer2_adf_dev_nvol`, exptr)
}

adf_dev_type <- function(exptr) {
  .Call(`_adfExplorer2_adf_dev_type`, exptr)
}

adf_free_blocks <- function(exptr, vol_num) {
  .Call(`_adfExplorer2_adf_free_blocks`, exptr, vol_num)
}

adf_block_size <- function(exptr, vol_num) {
  .Call(`_adfExplorer2_adf_block_size`, exptr, vol_num)
}

adf_vol_size <- function(exptr, vol_num) {
  .Call(`_adfExplorer2_adf_vol_size`, exptr, vol_num)
}

adf_is_intl <- function(exptr, vol_num) {
  .Call(`_adfExplorer2_adf_is_intl`, exptr, vol_num)
}

adf_is_dircache <- function(exptr, vol_num) {
  .Call(`_adfExplorer2_adf_is_dircache`, exptr, vol_num)
}

adf_is_ffs <- function(exptr, vol_num) {
  .Call(`_adfExplorer2_adf_is_ffs`, exptr, vol_num)
}

adf_is_write_protected <- function(exptr) {
  .Call(`_adfExplorer2_adf_is_write_protected`, exptr)
}

adf_is_bootable <- function(exptr, vol_num) {
  .Call(`_adfExplorer2_adf_is_bootable`, exptr, vol_num)
}

adf_set_dev_name <- function(extptr, vol_num, new_name) {
  .Call(`_adfExplorer2_adf_set_dev_name`, extptr, vol_num, new_name)
}

open_adf_ <- function(filename, write_protected) {
  .Call(`_adfExplorer2_open_adf_`, filename, write_protected)
}

adf_file_con_ <- function(extptr, filename, writable) {
  .Call(`_adfExplorer2_adf_file_con_`, extptr, filename, writable)
}

adf_file_con_info <- function(extptr) {
  .Call(`_adfExplorer2_adf_file_con_info`, extptr)
}
